=== ChristopherWalz/WCF/XSD/language.xsd
<?xml version="1.0"?>
<!-- This file is used for xml files which install or update language items. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="language">
		<xs:complexType>
			<xs:choice>
				<!-- deprecated since 5.5 -->
				<xs:sequence>
					<xs:element name="category" type="category" maxOccurs="unbounded" />
				</xs:sequence>
				<!-- /deprecated since 5.5 -->
				<xs:sequence>
					<xs:element name="import" type="import" minOccurs="0" />
					<xs:element name="delete" type="delete" minOccurs="0" />
				</xs:sequence>
			</xs:choice>
			<xs:attribute name="languagecode" type="woltlab_varchar" use="required" />
			<xs:attribute name="languagename" type="woltlab_varchar" use="optional" />
			<xs:attribute name="countrycode" type="woltlab_varchar" use="optional" />
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="category" type="category" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="item" type="item" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- language category element type -->
	<xs:complexType name="category">
		<xs:sequence>
			<xs:element name="item" type="item" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="woltlab_varchar" use="required" />
	</xs:complexType>
	
	<!-- language item element type -->
	<xs:complexType name="item" mixed="true">
		<xs:attribute name="name" type="woltlab_varchar" use="required" />
	</xs:complexType>
</xs:schema>

=== ChristopherWalz/WCF/wcfsetup/setup/lang/setup_de.xml
<?xml version="1.0" encoding="UTF-8"?>
<language xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com http://www.woltlab.com/XSD/6.0/language.xsd" languagecode="de" languagename="Deutsch">
	<category name="wcf.global">
		<item name="wcf.global.title"><![CDATA[WoltLab Suite&trade; Installation]]></item>
		<item name="wcf.global.pageDirection"><![CDATA[ltr]]></item>
		<item name="wcf.global.button.next"><![CDATA[Weiter »]]></item>
		<item name="wcf.global.progressBar"><![CDATA[{@$progress}% fertiggestellt]]></item>
		<item name="wcf.global.welcome"><![CDATA[Vielen Dank, dass Sie sich für WoltLab Suite&trade; entschieden haben!]]></item>
		<item name="wcf.global.welcome.description"><![CDATA[Dieser Installationsassistent hilft Ihnen bei der Einrichtung von <strong>WoltLab Suite&trade;</strong>.]]></item>
		<item name="wcf.global.welcome.language"><![CDATA[Sprache]]></item>
		<item name="wcf.global.welcome.language.description"><![CDATA[Die Sprache dieses Assistenten ist zurzeit {@$languageChooser}]]></item>
		<item name="wcf.global.welcome.language.change"><![CDATA[Sprache wechseln]]></item>
		<item name="wcf.global.license"><![CDATA[Lizenzbestimmungen]]></item>
		<item name="wcf.global.license.description"><![CDATA[Bitte lesen Sie die folgenden Lizenzbestimmungen. Verwenden Sie die Bildlaufleiste, um das gesamte Dokument anzuzeigen.]]></item>
		<item name="wcf.global.license.accept.description"><![CDATA[Akzeptieren Sie sämtliche Bedingungen der Lizenzbestimmungen? Sie können die Software nur installieren, wenn Sie die Lizenzbestimmungen akzeptieren.]]></item>
		<item name="wcf.global.license.missingAcception"><![CDATA[Um mit der Installation fortfahren zu können, müssen Sie die Lizenzbestimmungen akzeptieren.]]></item>
		<item name="wcf.global.systemRequirements.required"><![CDATA[Benötigte Systemvoraussetzungen]]></item>
		<item name="wcf.global.systemRequirements.recommended"><![CDATA[Empfohlene Systemvoraussetzungen]]></item>
		<item name="wcf.global.systemRequirements.element.required"><![CDATA[Benötigt]]></item>
		<item name="wcf.global.systemRequirements.element.yours"><![CDATA[Gefunden]]></item>
		<item name="wcf.global.systemRequirements.element.recommended"><![CDATA[Empfohlen]]></item>
		<item name="wcf.global.systemRequirements.php"><![CDATA[Installierte Version der Skriptsprache „PHP“]]></item>
		<item name="wcf.global.systemRequirements.php.description"><![CDATA[Die installierte Version der Skriptsprache „PHP“ liegt nicht im Bereich der unterstützten Versionen.]]></item>
		<item name="wcf.global.systemRequirements.sql"><![CDATA[PDO-Unterstützung]]></item>
		<item name="wcf.global.systemRequirements.sql.notFound"><![CDATA[nicht gefunden]]></item>
		<item name="wcf.global.systemRequirements.sql.description"><![CDATA[Ohne die „pdo_mysql“ PHP-Erweiterung kann diese Software nicht installiert werden.]]></item>
		<item name="wcf.global.systemRequirements.uploadMaxFilesize"><![CDATA[Maximale Größe für das Hochladen von Dateien]]></item>
		<item name="wcf.global.systemRequirements.uploadMaxFilesize.description"><![CDATA[Die derzeitige Konfiguration der Skriptsprache „PHP“ macht das Hochladen von Dateien unmöglich. Einige Funktionalitäten werden durch diese Konfiguration nur eingeschränkt funktionieren.]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary"><![CDATA[Grafikbearbeitungs-Bibliothek]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary.requirement"><![CDATA[GD Library oder ImageMagick]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary.description"><![CDATA[Die Grafikbearbeitungs-Bibliothek ist für die Verarbeitung und dynamische Generierung von Bildern zuständig. Es wird die GD Library oder alternativ ImageMagick benötigt.]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary.notFound"><![CDATA[nicht gefunden]]></item>
		<item name="wcf.global.systemRequirements.graphicsLibrary.webp"><![CDATA[Unterstützung für WebP-Grafiken fehlt]]></item>
		<item name="wcf.global.systemRequirements.active"><![CDATA[aktiviert]]></item>
		<item name="wcf.global.systemRequirements.notActive"><![CDATA[nicht aktiviert]]></item>
		<item name="wcf.global.systemRequirements.memoryLimit"><![CDATA[Zur Verfügung stehender Arbeitsspeicher]]></item>
		<item name="wcf.global.systemRequirements.memoryLimit.description"><![CDATA[Der PHP-Skripten zur Verfügung stehende Arbeitsspeicher ist für einen einwandfreien Betrieb der Software zu gering.]]></item>
		<item name="wcf.global.systemRequirements.openSSL"><![CDATA[„OpenSSL“ PHP-Erweiterung]]></item>
		<item name="wcf.global.systemRequirements.openSSL.description"><![CDATA[Ihre PHP-Version wurde ohne Unterstützung für OpenSSL kompiliert und kann daher keine sicheren Verbindungen aufbauen.]]></item>
		<item name="wcf.global.systemRequirements.curl"><![CDATA[„curl“ PHP-Erweiterung]]></item>
		<item name="wcf.global.systemRequirements.curl.description"><![CDATA[Ihre PHP-Version wurde ohne Unterstützung für cURL kompiliert. Die Unterstützung externer Verbindungen kann eingeschränkt sein.]]></item>
		<item name="wcf.global.systemRequirements.hostname"><![CDATA[Hostname]]></item>
		<item name="wcf.global.systemRequirements.hostname.requirement"><![CDATA[Korrekter Hostname]]></item>
		<item name="wcf.global.systemRequirements.hostname.description"><![CDATA[Der vom Webserver ermittelte Hostname muss dem Hostnamen in der Adressleiste des Webbrowsers entsprechen.]]></item>
		<item name="wcf.global.systemRequirements.cookie"><![CDATA[Cookies]]></item>
		<item name="wcf.global.systemRequirements.cookie.description"><![CDATA[Gesetzte Cookies müssen vom Webbrowser zurück an den Server gesendet werden.]]></item>
		<item name="wcf.global.systemRequirements.tls"><![CDATA[Verschlüsselte HTTPS-Verbindung (SSL/TLS)]]></item>
		<item name="wcf.global.systemRequirements.tls.description"><![CDATA[Die Installation wird über eine unverschlüsselte HTTP-Verbindung aufgerufen. Aus Gründen des Datenschutzes sollte der Zugriff generell über eine verschlüsselte HTTPS-Verbindung erfolgen. Unverschlüsselte Anfragen sollten auf die verschlüsselte Version umgeleitet werden. Bei der Verwendung von unverschlüsselten Verbindungen kann es zu einer Einschränkung des Funktionsumfangs kommen, da Webbrowser bestimmte Funktionen lediglich zur Verwendung mit verschlüsselten Verbindungen zulassen.]]></item>
		<item name="wcf.global.systemRequirements.x64"><![CDATA[64-Bit-Unterstützung]]></item>
		<item name="wcf.global.systemRequirements.x64.description"><![CDATA[Die eingesetzte PHP-Version muss die Verarbeitung von 64-Bit-Ganzzahlen unterstützen, um Zahlwerte größer als etwa 2,1 Milliarden korrekt zu verarbeiten.]]></item>
		<item name="wcf.global.next"><![CDATA[Lade nächsten Schritt …]]></item>
		<item name="wcf.global.next.description"><![CDATA[Die Installation lädt im Moment den nächsten Schritt. Bitte haben Sie einen Augenblick Geduld.]]></item>
		<item name="wcf.global.configureDB"><![CDATA[Datenbankzugang konfigurieren]]></item>
		<item name="wcf.global.configureDB.description"><![CDATA[Die Daten der Software werden in einer MySQL oder MariaDB-Datenbank gespeichert. Bitte geben Sie die Zugangsdaten für diese Datenbank an! Falls Ihnen die Zugangsdaten nicht bekannt sind, wenden Sie sich bitte an Ihren Serveradministrator oder Webhoster.]]></item>
		<item name="wcf.global.configureDB.host"><![CDATA[Server-Hostname]]></item>
		<item name="wcf.global.configureDB.user"><![CDATA[Benutzername]]></item>
		<item name="wcf.global.configureDB.password"><![CDATA[Kennwort]]></item>
		<item name="wcf.global.configureDB.database"><![CDATA[Datenbankname]]></item>
		<item name="wcf.global.configureDB.database.description"><![CDATA[Die spezifizierte Datenbank muss bereits angelegt sein.]]></item>
		<item name="wcf.global.configureDB.error"><![CDATA[Beim Verbindungsversuch mit der Datenbank ist folgender Fehler aufgetreten:
		<br><strong>{$exception->getMessage()}{if $exception->getPrevious()}<br>{$exception->getPrevious()->getMessage()}{/if}</strong>]]></item>
		<item name="wcf.global.configureDB.conflictedTables"><![CDATA[Folgende Tabelle{if $conflictedTables|count > 1}n{/if} existier{if $conflictedTables|count > 1}en{else}t{/if} schon in der Datenbank „{$dbName}“:<br>{implode from=$conflictedTables item="table"}{$table}{/implode}.<br><br>Um dieses Problem zu beheben, können Sie:<br>1. diese Tabelle{if $conflictedTables|count > 1}n{/if} manuell löschen und die „Weiter“ Schaltfläche betätigen, oder<br>2. Sie geben die Daten einer anderen Datenbank ein und betätigen die „Weiter“ Schaltfläche.]]></item>
		<item name="wcf.global.createUser"><![CDATA[Administrator erstellen]]></item>
		<item name="wcf.global.createUser.description"><![CDATA[Der Installationsassistent erstellt nun ein Administrator-Konto für Sie. Bitte geben Sie dazu einen Benutzernamen, eine E-Mail-Adresse und ein Kennwort ein.]]></item>
		<item name="wcf.global.createUser.username"><![CDATA[Benutzername]]></item>
		<item name="wcf.global.createUser.email"><![CDATA[E-Mail-Adresse]]></item>
		<item name="wcf.global.createUser.confirmEmail"><![CDATA[E-Mail-Adresse wiederholen]]></item>
		<item name="wcf.global.createUser.password"><![CDATA[Kennwort]]></item>
		<item name="wcf.global.createUser.confirmPassword"><![CDATA[Kennwort wiederholen]]></item>
		<item name="wcf.global.createUser.error"><![CDATA[Es sind Fehler bei Ihrer Registrierung aufgetreten. Bitte überprüfen Sie die markierten Felder.]]></item>
		<item name="wcf.global.createUser.error.empty"><![CDATA[Bitte füllen Sie dieses Eingabefeld aus.]]></item>
		<item name="wcf.global.createUser.error.username.invalid"><![CDATA[Der eingegebene Benutzername ist ungültig. Ein gültiger Benutzername muss mindestens 3 und maximal 20 Zeichen lang sein.]]></item>
